---
sudo: false
language: python
os:
  - linux
python:
  - "3.6"
  - "3.7-dev"

git:
  depth: 2

cache: pip

branches:
  only:
  - master
  - devel
  - "/^\\d+\\.\\d+\\.\\d+[a]?\\d*$/"

env:
  global:
    - GITHUB_REPO=Midnighter/BRENDA-parser

matrix:
  fast_finish: true

install:
  - pip install --upgrade pip setuptools wheel tox tox-travis

script:
  - tox -- --cov-report=xml
after_success:
  - bash <(curl -f https://codecov.io/bash)

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      python: "3.6"
      install:
        - pip install --upgrade setuptools wheel
      script: skip
      after_success: echo "Deploying..."
      deploy:
        - provider: pypi
          skip_cleanup: true
          distributions: sdist bdist_wheel
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true
            repo: $GITHUB_REPO
        - provider: releases
          skip_cleanup: true
          api_key: $GITHUB_TOKEN
          body: "Please see https://github.com/${GITHUB_REPO}/blob/${TRAVIS_TAG}/CHANGELOG.rst for the full release notes."
          on:
            tags: true
            repo: $GITHUB_REPO

notifications:
  email:
    on_success: never
    on_failure: always
    on_pull_requests: never
