language: python
sudo: false
cache: pip
git:
  depth: 1
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+\\.\\d+[a]?\\d*$/"
matrix:
  fast_finish: true
  include:
    - python: '3.5'
      env:
        - TOXENV=flake8
    - python: '2.7'
      env:
        - TOXENV=py27
    - python: '3.5'
      env:
        - TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - travis_retry pip install -U pip setuptools wheel tox
script:
  - travis_wait tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
